name = "REopt"
uuid = "d36ad4e8-d74a-4f7a-ace1-eaea049febf6"
authors = ["Nick Laws", "Hallie Dunham <hallie.dunham@nrel.gov>", "Bill Becker <william.becker@nrel.gov>", "Bhavesh Rathod <bhavesh.rathod@nrel.gov>", "Alex Zolan <alexander.aolan@nrel.gov>", "Amanda Farthing <amanda.farthing@nrel.gov>"]
version = "0.38.1"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CoolProp = "e084ae63-2819-5025-826e-f8e611a84251"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinDistFlow = "bf674bac-ffe4-48d3-9f32-72124ffa9ede"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"

[compat]
ArchGDAL = "0.8, 0.9"
CoolProp = "0.1"
CSV = "0.10"
DataFrames = "1.4"
HTTP = "0.8, 0.9, 1"
JLD = "0.13"
JSON = "0.21"
JuMP = "0.21, 0.22, 0.23, 1"
LinDistFlow = "0.1, 0.2"
MathOptInterface = "0.9, 0.10, 1"
Requires = "1.3"
Roots = "1.3, 2"
TestEnv = "1.7, 1.8, 1.9"
Dates = "1"
DelimitedFiles = "1"
LinearAlgebra = "1"
Logging = "1"
Statistics = "1"
julia = "1.4, 1.5, 1.6, 1.7, 1.8"
